spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.167:3306/test
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl: 
          auto: update
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
